### ISSUE TITLE
Selecting invalid class

### ISSUE THREAD

**Issue by Laffini** [Laffini/student-analyisation#1]
Currently it is possible to select an invalid class after how many classes has been asked and then what the file(s) is/are called.
-Create a try for the error.

Example:
How many classes do you have? 1
What is your file called? class4
Which class would you like to see the data for? class4
Traceback (most recent call last):
  File "C:\Users\Laffy\Desktop\Task 3\StudentAnalysis.py", line 102, in <module>
    analyse()
  File "C:\Users\Laffy\Desktop\Task 3\StudentAnalysis.py", line 43, in analyse
    file = open('%s.csv' %classchoice)
FileNotFoundError: [Errno 2] No such file or directory: 'class4.csv'

**Comment by Laffini** [comment]
Sorted by setting up a try so that it restarts if it can't open the file. Looking for a better fix ASAP. Had to add an additional layer of a defined function.
